<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug_Ubuntu;Debug;Release_Ubuntu;Release</Configurations>
    <ApplicationIcon>ScriptPlayerIcon.ico</ApplicationIcon>
    <StartupObject>ScriptPlayer.App</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <PackageReference Include="10" Version="0.17763.0" />
    <PackageReference Include="FMUtils.KeyboardHook" Version="1.0.140.2145" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.43" />
    <PackageReference Include="JetBrains.Annotations" Version="2022.1.0" />
    <PackageReference Include="MediaInfo.Native" Version="21.9.1" />
    <PackageReference Include="MediaInfo.Wrapper" Version="21.9.2" />
    <PackageReference Include="Microsoft.WindowsAPICodePack-Core" Version="1.1.0.2" />
    <PackageReference Include="Microsoft.WindowsAPICodePack-Shell" Version="1.1.0.0" />
    <PackageReference Include="NAudio" Version="2.1.0" />
    <PackageReference Include="NAudio.Asio" Version="2.1.0" />
    <PackageReference Include="NAudio.Core" Version="2.1.0" />
    <PackageReference Include="NAudio.Midi" Version="2.1.0" />
    <PackageReference Include="NAudio.Wasapi" Version="2.1.0" />
    <PackageReference Include="NAudio.WinForms" Version="2.1.0" />
    <PackageReference Include="NAudio.WinMM" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Octokit" Version="0.51.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.2.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScriptPlayer.HandyApi\ScriptPlayer.HandyApi.csproj" />
    <ProjectReference Include="..\ScriptPlayer.Ipc\ScriptPlayer.Ipc.csproj" />
    <ProjectReference Include="..\ScriptPlayer.Shared\ScriptPlayer.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="ScriptPlayerIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ScriptPlayerIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\FMUtils.KeyboardHook.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\FolderBrowserDialogEx.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\JetBrains.Annotations.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\Newtonsoft.Json.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\NLog.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\Octokit.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\Buttplug.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\deniszykov.WebSocketListener.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\HtmlAgilityPack.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\MediaInfo.Native.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\MediaInfo.Wrapper.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\NJsonSchema.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\SuperSocket.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\WebSocket4Net.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\YamlDotNet.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\ScriptPlayer.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Licenses\FontAwesome.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\VideoPreview.png" />
  </ItemGroup>
</Project>