<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>spcli</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug_Ubuntu;Debug;Release_Ubuntu;Release</Configurations>
    <StartupObject>ScriptPlayer.Cli.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScriptPlayer.Ipc\ScriptPlayer.Ipc.csproj" />
  </ItemGroup>
</Project>